# ============================
# EMAIL (Brevo REST API)
# ============================
BREVO_API_KEY=${BREVO_API_KEY}
BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}

# ============================
# DATABASE
# ============================
spring.application.name=project-spring
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================
# FILE UPLOAD
# ============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ============================
# OAUTH2
# ============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# ============================
# SERVER
# ============================
server.port=${PORT:8080}